import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import projects from "../projects.json";

const Home: NextPage = () => {
  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>Patrick Fender - Web Development Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          
        </div>
      </main> */}
      <nav className="bg-gray-800">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <Image src="/logo.svg" alt="Logo" width={32} height={32} />
              </div>
              <div className="hidden md:block">
                <div className="ml-10 flex items-baseline space-x-4">
                  <Link href="#about">
                    <p className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">
                      About
                    </p>
                  </Link>
                  <Link href="#portfolio">
                    <p className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">
                      Portfolio
                    </p>
                  </Link>
                  <Link href="#contact">
                    <p className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">
                      Contact
                    </p>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <div className="bg-gradient-to-b from-[#2e026d] to-[#15162c] py-16 text-center">
        {/* bg-gradient-to-b from-[#2e026d] to-[#15162c] */}
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Hi, I'm <span className="text-[hsl(280,100%,70%)]">Patrick</span> 👋
        </h1>
        {/* <h1 className="text-4xl font-bold text-gray-900">My Name</h1>
          <p className="mt-4 text-lg text-gray-500">
            Web Developer based in Some City, Country
          </p> */}
      </div>
      <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <section id="about" className="mt-16">
          <div className="mx-auto max-w-lg">
            <h2 className="mb-8 text-3xl font-bold">About Me</h2>
            <p className="text-lg text-gray-500">
              I’m a passionate &lt;web developer&gt; with a love for all things
              technology! Currently I am studying computer science in Darmstadt,
              Germany.
            </p>
          </div>
        </section>

        <section id="portfolio" className="mt-16">
          <div className="mx-auto max-w-5xl">
            <h2 className="mb-8 text-3xl font-bold">My Projects</h2>
            <ul className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {projects.map((project) => (
                <li
                  key={project.name}
                  className="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow"
                >
                  <div className="w-1/3">
                    <Image
                      className="rounded-lg"
                      src={project.image}
                      alt={project.name}
                      width={300}
                      height={200}
                    />
                  </div>
                  <div className="flex-1 p-6">
                    <h3 className="text-lg font-medium text-gray-900">
                      {project.name}
                    </h3>
                    <div className="mt-2 text-sm text-gray-500">
                      {project.description}
                    </div>
                    <div className="mt-4">
                      {project.tags.map((tag) => (
                        <span
                          key={tag}
                          className="mr-2 inline-block rounded-full bg-gray-200 px-3 py-1 text-sm font-semibold text-gray-700"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                    <div className="mt-4">
                      <a
                        href={project.demoLink}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-indigo-600 hover:text-indigo-500"
                      >
                        Live Demo
                      </a>
                      <span className="mx-2 text-gray-500">|</span>
                      <a
                        href={project.githubLink}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-indigo-600 hover:text-indigo-500"
                      >
                        Source Code
                      </a>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section id="contact" className="mt-16">
          <div className="mx-auto max-w-lg">
            <h2 className="mb-8 text-3xl font-bold">Get In Touch</h2>
            <p className="text-lg text-gray-500">
              Have a question or want to work together? Feel free to send me an
              email at{" "}
              <a
                href="mailto:hello@patrickfender.com"
                className="text-indigo-600 hover:text-indigo-500"
              >
                hello@patrickfender.com
              </a>
              .
            </p>
          </div>
          <div className="mt-8 flex justify-center">
            <button className="rounded-lg bg-indigo-600 px-6 py-3 text-white shadow-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50">
              Send E-Mail
            </button>
          </div>
        </section>
      </main>
      <div className="py-4"></div>
      <footer className="mt-auto bg-gray-800 px-6 py-4 text-white">
        <p>© 2023 Your Name. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Home;
