import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import { faArrowUpRightFromSquare } from "@fortawesome/free-solid-svg-icons";
import { faEnvelope } from "@fortawesome/free-regular-svg-icons";
import { faBook } from "@fortawesome/free-solid-svg-icons";
import About from "~/components/About";
import Navbar from "~/components/Navbar";
import TechStack from "~/components/TechStack";
import Portfolio from "~/components/Portfolio";
import Contact from "~/components/Contact";
import Footer from "~/components/Footer";

const Home: NextPage = () => {
  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>Patrick Fender - Web Development Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section id="about">
        <About />
      </section>
      <main className="mx-auto  px-4 sm:px-12 lg:px-24">
        <section id="techstack" className="mt-16 bg-indigo-100 px-8 py-12">
          <TechStack />
        </section>
        <section id="portfolio" className="mt-16">
          <Portfolio />
        </section>
        <section
          id="contact"
          className="mt-16 rounded-xl bg-indigo-900 px-8 py-12 text-white shadow"
        >
          <Contact />
        </section>
      </main>
      <div className="py-4"></div>
      <Footer />
    </div>
  );
};

export default Home;
